---
title: "practical_exercise_8 , Methods 3, 2021, autumn semester"
author: '[FILL IN YOUR NAME]'
date: "[FILL IN THE DATE]"
output: html_document
---

<style type="text/css">
  body{
  font-size: 14pt;
}
</style>


# Exercises and objectives

1) Load the magnetoencephalographic recordings and do some initial plots to understand the data  
2) Do logistic regression to classify pairs of PAS-ratings  
3) Do a Support Vector Machine Classification on all four PAS-ratings  

REMEMBER: In your report, make sure to include code that can reproduce the answers requested in the exercises below (__MAKE A KNITTED VERSION__)  
REMEMBER: This is Assignment 3 and will be part of your final portfolio   

# EXERCISE 1 - Load the magnetoencephalographic recordings and do some initial plots to understand the data  

The files `megmag_data.npy` and `pas_vector.npy` can be downloaded here (http://laumollerandersen.org/data_methods_3/megmag_data.npy) and here (http://laumollerandersen.org/data_methods_3/pas_vector.npy)   


```{python}
# Load in packages
import numpy as np
import matplotlib.pyplot as plt
import os

two_d = np.array([[1,2,3,4],[2,3,4,5]])
two_d
two_d.shape
np.mean(two_d, axis=0)

three_d = np.array([[[1,2,3,4],[2,3,4,5]], [[10,9,8,7], [7,6,5,4]], [[7,6,5,4], [7,8,9,10]]])
three_d
three_d.shape
np.mean(three_d, axis=0)
np.mean(three_d, axis=0).shape


```

1.1
Load `megmag_data.npy` and call it `data` using `np.load`. You can use `join`, which can be imported from `os.path`, to create paths from different string segments  
```{python}
data = np.load(os.path.join("data", "megmag_data.npy"))
```

1.1.i The data is a 3-dimensional array. The first dimension is number of repetitions of a visual stimulus , the second dimension is the number of sensors that record magnetic fields (in Tesla) that stem from neurons activating in the brain, and the third dimension is the number of time samples. How many repetitions, sensors and time samples are there? 
```{python}
data.shape
# 682 repetitions (trials)
# 102 n_sensors
# 251 time points
```
 
1.1.ii. The time range is from (and including) -200 ms to (and including) 800 ms with a sample recorded every 4 ms. At time 0, the visual stimulus was briefly presented. Create a 1-dimensional array called `times` that represents this.  
```{python}
# Make a range of numbers, from -200 to 801, with increments of 4
times = np.arange(-200, 801, 4)

# See that it fits with 251 time points
len(times) == 251

```

1.1.iii. Create the sensor covariance matrix $\Sigma_{XX}$: $$\Sigma_{XX} = \frac 1 N \sum_{i=1}^N XX^T$$ $N$ is the number of repetitions and $X$ has $s$ rows and $t$ columns (sensors and time), thus the shape is $X_{s\times t}$. Do the sensors pick up independent signals? (Use `plt.imshow` to plot the sensor covariance matrix)  
```{python}
# Define N (from formula)
N = data.shape[0]

# For each trial, multiply the matrix with itself (one of them transposed) as in formula. Append to list
matrices = []
for trial in np.arange(N):
  matrix = data[trial, :, :] @ data[trial, :, :].T
  matrices.append(matrix)

# Compute covariance matrix
cov_matrix = (1/N)*sum(matrices)

# Plot covariance matrix
plt.figure()
plt.imshow(cov_matrix, vmin=-5e-23, vmax=5e-23)
plt.colorbar()
plt.show()

# No they don't
```

1.1.iv. Make an average over the repetition dimension using `np.mean` - use the `axis` argument. (The resulting array should have two dimensions with time as the first and magnetic field as the second)  
```{python}
#### Can we draw what happens? Hard to conceptualize

# Take averages along the 0th axis (trials)
average = np.mean(data, axis=0)
# Before we had a score per trial, per sensor, per time.
# Now we have an average score per sensor, per time.

#Check that first dimension should be time, and second should be sensor
average.shape

# It is not the case, so we may transpose
average = average.T
```

1.1.v. Plot the magnetic field (based on the average) as it evolves over time for each of the sensors (a line for each) (time on the x-axis and magnetic field on the y-axis). Add a horizontal line at $y = 0$ and a vertical line at $x = 0$ using `plt.axvline` and `plt.axhline`  
```{python}
plt.figure()
plt.plot(times, average)
plt.axvline(color='k')
plt.axhline(color='k')
plt.show()

# Now we can see the microvolts over time, across sensors/channels

```

1.1.vi. Find the maximal magnetic field in the average. Then use `np.argmax` and `np.unravel_index` to find the sensor that has the maximal magnetic field.  
```{python}
# Find max value
max_value = np.max(average)

# Get index of max value
max_time_idx, max_sensor_idx = np.where(average == max_value)

# Check that you have found it
average[max_time_idx, max_sensor_idx]

max_time_idx
max_sensor_idx

# The max value is found in sensor with index 73, at time point with index 112

```

1.1.vii. Plot the magnetic field for each of the repetitions (a line for each) for the sensor that has the maximal magnetic field. Highlight the time point with the maximal magnetic field in the average (as found in 1.1.v) using `plt.axvline`
```{python}
# Check which dimension had sensors
data.shape

plt.figure()
plt.plot(times, data[:, int(max_sensor_idx), :].T) # Take the data, but only for the sensor 73. Transpose, also
plt.axvline(color='k')
plt.axhline(color='k')
plt.axvline(x=times[max_time_idx], linestyle='--', color='k') # Plot a line at the timepoint with largest value
plt.show()

```

1.1.viii. Describe in your own words how the response found in the average is represented in the single repetitions. But do make sure to use the concepts _signal_ and _noise_ and comment on any differences on the range of values on the y-axis  
```{python}
# Each of the single trials contain signal + noise. Since the noise is random, we can signal it out by averaging across trials.
```


1.2. Now load `pas_vector.npy` (call it `y`). PAS is the same as in Assignment 2, describing the clarity of the subjective experience the subject reported after seeing the briefly presented stimulus  
```{python}
y = np.load(os.path.join("data", "pas_vector.npy"))


```

1.2.i. Which dimension in the `data` array does it have the same length as?  
```{python}
data.shape
len(y)

# Trials and y have same length
```

1.2.ii. Now make four averages (As in Exercise 1.1.iii), one for each PAS rating, and plot the four time courses (one for each PAS rating) for the sensor found in Exercise ~~1.1.v~~  1.1.vi
```{python}
# Get all unique PAS ratings
PAS = np.unique(y)

avgs = [] # Initialize empty list for appending to
for i in PAS:
  data_subset = data[y == i, :, :] # Take all data, but only for trials that were rated as 1, 2, 3, 4 (for each loop) in PAS.
  avg = np.mean(data_subset, axis = 0) # Take mean across all sensors and timepoints
  avgs.append(avg) # Append to list

plt.figure()
# For each of the 4 PAS-rating subset, averages. Plot times on the x-axis, and the average (but only for sensor 73) on the y-axis
for avg in avgs:
    plt.plot(times, avg[int(max_sensor_idx), :])
plt.axhline(color='k')
plt.axvline(color='k')
plt.legend(PAS)
plt.show()

# Now we have a plot showing the average voltages for trials with different ratings.
```

1.2.iii. Notice that there are two early peaks (measuring visual activity from the brain), one before 200 ms and one around 250 ms. Describe how the amplitudes of responses are related to the four PAS-scores. Does PAS 2 behave differently than expected?  
```{python}
# Didn't expect anything. We see that P2 has largest N1 and P1. 
#Perhaps larger activity when analyzing harder. PAS 1 = Too hard to try and process what we saw. PAS 3, 4, too easy? Hard to know

```

# EXERCISE 2 - Do logistic regression to classify pairs of PAS-ratings  

2.1 Now, we are going to do Logistic Regression with the aim of classifying the PAS-rating given by the subject  

2.1.i. We'll start with a binary problem - create a new array called `data_1_2` that only contains PAS responses 1 and
    2. Similarly, create a `y_1_2` for the target vector  
```{python}
# Subset
data_1_2 = data[y < 3, :, :]
y_1_2 = y[y < 3]

```

2.1.ii. Scikit-learn expects our observations (`data_1_2`) to be in a 2d-array, which has samples (repetitions) on dimension 1 and features (predictor variables) on dimension 2. Our `data_1_2` is a three-dimensional array. Our strategy will be to collapse our two last dimensions (sensors and time) into one dimension, while keeping the first dimension as it is (repetitions). Use `np.reshape` to create a variable `X_1_2` that fulfils these criteria.  
```{python}
# ini_array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
# ini_array1.shape
# ini_array1.flatten()

#### What do you mean by "collapsing" the array? 
# Is it just flattening the array / Concatenating the values as shown below? 
# So that we get [s1t1, s1t2, s1t3 ... s102t251]

data_1_2.shape
X_1_2 = data_1_2.reshape(214, -1)
X_1_2.shape

# Before we had a score per trial, per sensor, per time.
# Now we have an average score per sensor, per time.
```

2.1.iii. Import the `StandardScaler` and scale `X_1_2`  
```{python}
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_1_2 = sc.fit_transform(X_1_2)
```

2.1.iv. Do a standard `LogisticRegression` - can be imported from `sklearn.linear_model` - make sure there is no `penalty` applied  
```{python}
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(penalty='none')
lr.fit(X_1_2, y_1_2)
lr.score()

```

2.1.v. Use the `score` method of `LogisticRegression` to find out how many labels were classified correctly. Are we overfitting? Besides the score, what would make you suspect that we are overfitting?  
```{python}

```

2.1.vi. Now apply the _L1_ penalty instead - how many of the coefficients (`.coef_`) are non-zero after this?  
```{python}

```

2.1.vii. Create a new reduced $X$ that only includes the non-zero coefficients - show the covariance of the non-zero features (two covariance matrices can be made; $X_{reduced}X_{reduced}^T$ or $X_{reduced}^TX_{reduced}$ (you choose the right one)) . Plot the covariance of the features using `plt.imshow`. Compared to the plot from 1.1.iii, do we see less covariance?  
```{python}
# Forming groups of group size = 2. Group forming has to be outside study groups
groups = group_up(group_size=2, outside_studygroup=True)

# For group in groups
for group in groups:
  
  # While time is smaller than 11:10
  while time < 11:10:
    
    # Do over the shoulder programming. When finished computing, done == True
    done = over_the_shoulder(group)
    
    # If done, do pair-wise programming
    if done = True:
      pair_wise_programming(group)
  
  # When time is not smaller than 11:10
  pair_wise_programming(group)
```

2.2. Now, we are going to build better (more predictive) models by using cross-validation as an outcome measure    
```{python}

```

2.2.i. Import `cross_val_score` and `StratifiedKFold` from `sklearn.model_selection`  
```{python}

```

2.2.ii. To make sure that our training data sets are not biased to one target (PAS) or the other, create `y_1_2_equal`, which should have an equal number of each target. Create a similar `X_1_2_equal`. The function `equalize_targets_binary` in the code chunk associated with Exercise 2.2.ii can be used. Remember to scale `X_1_2_equal`!  
```{python}

```

2.2.iii. Do cross-validation with 5 stratified folds doing standard `LogisticRegression` (See Exercise 2.1.iv)  
```{python}

```

2.2.iv. Do L2-regularisation with the following `Cs=  [1e5, 1e1, 1e-5]`. Use the same kind of cross-validation as in Exercise 2.2.iii. In the best-scoring of these models, how many more/fewer predictions are correct (on average)?  
```{python}

```

2.2.v. Instead of fitting a model on all `n_sensors * n_samples` features, fit  a logistic regression (same kind as in Exercise 2.2.iv (use the `C` that resulted in the best prediction)) for __each__ time sample and use the same cross-validation as in Exercise 2.2.iii. What are the time points where classification is best? Make a plot with time on the x-axis and classification score on the y-axis with a horizontal line at the chance level (what is the chance level for this analysis?)  
```{python}

```

2.2.vi. Now do the same, but with L1 regression - set `C=1e-1` - what are the time points when classification is best? (make a plot)?  
```{python}

```

2.2.vii. Finally, fit the same models as in Exercise 2.2.vi but now for `data_1_4` and `y_1_4` (create a data set and a target vector that only contains PAS responses 1 and 4). What are the time points when classification is best? Make a plot with time on the x-axis and classification score on the y-axis with a horizontal line at the chance level (what is the chance level for this analysis?)  
```{python}

```

2.3. Is pairwise classification of subjective experience possible? Any surprises in the classification accuracies, i.e. how does the classification score fore PAS 1 vs 4 compare to the classification score for PAS 1 vs 2?  
```{python}

```


```{python, eval=FALSE}
# Exercise 2.2.ii
def equalize_targets_binary(data, y):
    np.random.seed(7)
    targets = np.unique(y) ## find the number of targets
    if len(targets) > 2:
        raise NameError("can't have more than two targets")
    counts = list()
    indices = list()
    for target in targets:
        counts.append(np.sum(y == target)) ## find the number of each target
        indices.append(np.where(y == target)[0]) ## find their indices
    min_count = np.min(counts)
    # randomly choose trials
    first_choice = np.random.choice(indices[0], size=min_count, replace=False)
    second_choice = np.random.choice(indices[1], size=min_count,replace=False)
    
    # create the new data sets
    new_indices = np.concatenate((first_choice, second_choice))
    new_y = y[new_indices]
    new_data = data[new_indices, :, :]
    
    return new_data, new_y
```

# EXERCISE 3 - Do a Support Vector Machine Classification on all four PAS-ratings  
1) Do a Support Vector Machine Classification  
    i. First equalize the number of targets using the function associated with each PAS-rating using the function associated with Exercise 3.1.i  
    ii. Run two classifiers, one with a linear kernel and one with a radial basis (other options should be left at their defaults) - the number of features is the number of sensors multiplied the number of samples. Which one is better predicting the category?
    iii. Run the sample-by-sample analysis (similar to Exercise 2.2.v) with the best kernel (from Exercise 3.1.ii). Make a plot with time on the x-axis and classification score on the y-axis with a horizontal line at the chance level (what is the chance level for this analysis?)
    iv. Is classification of subjective experience possible at around 200-250 ms?  
2) Finally, split the equalized data set (with all four ratings) into a training part and test part, where the test part if 30 % of the trials. Use `train_test_split` from `sklearn.model_selection`  
    i. Use the kernel that resulted in the best classification in Exercise 3.1.ii and `fit`the training set and `predict` on the test set. This time your features are the number of sensors multiplied by the number of samples.  
    ii. Create a _confusion matrix_. It is a 4x4 matrix. The row names and the column names are the PAS-scores. There will thus be 16 entries. The PAS1xPAS1 entry will be the number of actual PAS1, $y_{pas1}$ that were predicted as PAS1, $\hat y_{pas1}$. The PAS1xPAS2 entry will be the number of actual PAS1, $y_{pas1}$ that were predicted as PAS2, $\hat y_{pas2}$ and so on for the remaining 14 entries.  Plot the matrix
    iii. Based on the confusion matrix, describe how ratings are misclassified and if that makes sense given that ratings should measure the strength/quality of the subjective experience. Is the classifier biased towards specific ratings?  
    
```{python, eval=FALSE}

def equalize_targets(data, y):
    np.random.seed(7)
    targets = np.unique(y)
    counts = list()
    indices = list()
    for target in targets:
        counts.append(np.sum(y == target))
        indices.append(np.where(y == target)[0])
    min_count = np.min(counts)
    first_choice = np.random.choice(indices[0], size=min_count, replace=False)
    second_choice = np.random.choice(indices[1], size=min_count, replace=False)
    third_choice = np.random.choice(indices[2], size=min_count, replace=False)
    fourth_choice = np.random.choice(indices[3], size=min_count, replace=False)
    
    new_indices = np.concatenate((first_choice, second_choice,
                                 third_choice, fourth_choice))
    new_y = y[new_indices]
    new_data = data[new_indices, :, :]
    
    return new_data, new_y

```